# Generated by Django 5.2.2 on 2026-07-27 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planos', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='assinatura',
            new_name='planos_assi_status_e82c47_idx',
            old_name='planos_assi_status_idx',
        ),
        migrations.RenameIndex(
            model_name='assinatura',
            new_name='planos_assi_cancela_6246d2_idx',
            old_name='planos_assi_cancel_idx',
        ),
    ]
