# Generated by Django 5.2.2 on 2026-06-09 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negocios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('view', 'Visualizacao da pagina'), ('whatsapp', 'Clique no WhatsApp'), ('produto', 'Visualizacao de produto'), ('share', 'Compartilhamento'), ('instagram', 'Clique no Instagram'), ('tiktok', 'Clique no TikTok'), ('facebook', 'Clique no Facebook'), ('youtube', 'Clique no YouTube'), ('maps', 'Clique no Maps')], max_length=20)),
                ('origem', models.CharField(choices=[('google', 'Google'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('whatsapp', 'WhatsApp'), ('direto', 'Acesso direto'), ('outro', 'Outro')], default='direto', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliques', to='negocios.negocio')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliques', to='negocios.produto')),
            ],
            options={
                'verbose_name': 'Clique',
                'verbose_name_plural': 'Cliques',
                'indexes': [models.Index(fields=['negocio', 'criado_em'], name='analytics_c_negocio_9dd49d_idx'), models.Index(fields=['negocio', 'tipo', 'criado_em'], name='analytics_c_negocio_836b3e_idx')],
            },
        ),
        migrations.CreateModel(
            name='MetricaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('total_views', models.IntegerField(default=0)),
                ('total_produto', models.IntegerField(default=0)),
                ('total_whatsapp', models.IntegerField(default=0)),
                ('total_shares', models.IntegerField(default=0)),
                ('origem_google', models.IntegerField(default=0)),
                ('origem_instagram', models.IntegerField(default=0)),
                ('origem_facebook', models.IntegerField(default=0)),
                ('origem_whatsapp', models.IntegerField(default=0)),
                ('origem_direto', models.IntegerField(default=0)),
                ('cliques_instagram', models.IntegerField(default=0)),
                ('cliques_tiktok', models.IntegerField(default=0)),
                ('cliques_facebook', models.IntegerField(default=0)),
                ('cliques_youtube', models.IntegerField(default=0)),
                ('cliques_maps', models.IntegerField(default=0)),
                ('taxa_conversao', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metricas', to='negocios.negocio')),
            ],
            options={
                'verbose_name': 'Metrica Diaria',
                'verbose_name_plural': 'Metricas Diarias',
                'indexes': [models.Index(fields=['negocio', 'data'], name='analytics_m_negocio_498d56_idx')],
                'unique_together': {('negocio', 'data')},
            },
        ),
    ]
