# Generated by Django 5.2.2 on 2026-07-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_token_version',
            field=models.IntegerField(default=0),
        ),
    ]
