# Generated by Django 5.2.2 on 2026-06-08 23:53

import django.db.models.deletion
import negocios.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=negocios.models.gerar_caminho_seguro)),
                ('cidade', models.CharField(max_length=100)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('whatsapp', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True)),
                ('plano', models.CharField(choices=[('gratuito', 'Gratuito'), ('basico', 'Básico — R$ 79/mês'), ('pro', 'Pro — R$ 197/mês'), ('producao', 'Produção — R$ 397/mês'), ('fundador', 'Fundador — R$ 599/ano')], default='gratuito', max_length=20)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('pendente', 'Pendente')], default='pendente', max_length=20)),
                ('verificado', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('seo_title', models.CharField(blank=True, max_length=60)),
                ('seo_description', models.CharField(blank=True, max_length=160)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to=negocios.models.gerar_caminho_seguro)),
                ('alt_logo', models.CharField(blank=True, max_length=125)),
                ('categoria_tipo', models.CharField(blank=True, max_length=50)),
                ('palavras_chave', models.CharField(blank=True, max_length=300)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('horario_abertura', models.TimeField(blank=True, null=True)),
                ('horario_fechamento', models.TimeField(blank=True, null=True)),
                ('dias_funcionamento', models.JSONField(blank=True, default=list)),
                ('media_nota', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_avaliacoes', models.IntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='negocios', to='categorias.categoria')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='negocio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Negócio',
                'verbose_name_plural': 'Negócios',
            },
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccao', models.CharField(max_length=300)),
                ('direccao_fmt', models.CharField(blank=True, max_length=300)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('cep', models.CharField(blank=True, max_length=9)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('area_servico', models.CharField(blank=True, max_length=300)),
                ('negocio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='localizacao', to='negocios.negocio')),
            ],
            options={
                'verbose_name': 'Localização',
                'verbose_name_plural': 'Localizações',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=negocios.models.gerar_caminho_seguro)),
                ('descricao', models.TextField(blank=True)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('disponivel', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('confirmado_em', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('alt_foto', models.CharField(blank=True, max_length=125)),
                ('descricao_longa', models.TextField(blank=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='negocios.negocio')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='RedesSociais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_url', models.URLField(blank=True)),
                ('tiktok_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('x_url', models.URLField(blank=True)),
                ('negocio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='redes_sociais', to='negocios.negocio')),
            ],
            options={
                'verbose_name': 'Redes Sociais',
                'verbose_name_plural': 'Redes Sociais',
            },
        ),
        migrations.CreateModel(
            name='VideoDestaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_original', models.URLField()),
                ('plataforma', models.CharField(max_length=20)),
                ('oembed_html', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='negocios.negocio')),
            ],
            options={
                'verbose_name': 'Vídeo Destaque',
                'verbose_name_plural': 'Vídeos Destaque',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='negocio',
            index=models.Index(fields=['cidade', 'status'], name='negocios_ne_cidade_66e3f6_idx'),
        ),
        migrations.AddIndex(
            model_name='negocio',
            index=models.Index(fields=['slug'], name='negocios_ne_slug_7e6b86_idx'),
        ),
        migrations.AddIndex(
            model_name='negocio',
            index=models.Index(fields=['plano', 'status'], name='negocios_ne_plano_9a10f8_idx'),
        ),
        migrations.AddIndex(
            model_name='negocio',
            index=models.Index(fields=['atualizado_em'], name='negocios_ne_atualiz_a06641_idx'),
        ),
        migrations.AddIndex(
            model_name='negocio',
            index=models.Index(fields=['verificado', 'status'], name='negocios_ne_verific_6165d3_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['negocio', 'disponivel'], name='negocios_pr_negocio_9a2861_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['disponivel', 'atualizado_em'], name='negocios_pr_disponi_525e20_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['confirmado_em'], name='negocios_pr_confirm_b1812d_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['slug'], name='negocios_pr_slug_6c9cc0_idx'),
        ),
    ]
