# Generated by Django 5.2.2 on 2026-06-14 20:07

import django.db.models.deletion
import negocios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0002_negocio_historia'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to=negocios.models.gerar_caminho_seguro)),
                ('alt_texto', models.CharField(blank=True, max_length=125)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='negocios.produto')),
            ],
            options={
                'verbose_name': 'Foto do Produto',
                'verbose_name_plural': 'Fotos do Produto',
                'ordering': ['ordem', 'criado_em'],
            },
        ),
    ]
