# Generated by Django 5.2.2 on 2026-06-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0003_fotoproduto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
