# Generated by Django 5.2.2 on 2026-06-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0004_produto_ordem'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='espaco_especial',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
