# Generated by Django 5.2.2 on 2026-07-05 19:46

from django.db import migrations, models


def split_direccao(apps, schema_editor):
    Localizacao = apps.get_model("negocios", "Localizacao")
    for loc in Localizacao.objects.all():
        if not loc.direccao:
            continue
        if "," in loc.direccao:
            partes = loc.direccao.split(",", 1)
            loc.logradouro = partes[0].strip()
            loc.numero = partes[1].strip()
        else:
            loc.logradouro = loc.direccao.strip()
            loc.numero = ""
        loc.save(update_fields=["logradouro", "numero"])


def reverse_split(apps, schema_editor):
    Localizacao = apps.get_model("negocios", "Localizacao")
    for loc in Localizacao.objects.all():
        if loc.logradouro:
            partes = [loc.logradouro]
            if loc.numero:
                partes.append(loc.numero)
            loc.direccao = ", ".join(partes)
            loc.save(update_fields=["direccao"])


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0006_unaccent_normalizar_cidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='localizacao',
            name='logradouro',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='localizacao',
            name='numero',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='localizacao',
            name='direccao',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.RunPython(split_direccao, reverse_split),
    ]
