# Generated by Django 5.2.2 on 2026-07-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0007_localizacao_split_endereco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redessociais',
            name='x_url',
        ),
        migrations.AddField(
            model_name='redessociais',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
    ]
