# Generated by Django 5.2.2 on 2026-07-27 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0011_produto_tipo_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='plano',
            field=models.CharField(choices=[('gratuito', 'Presença Sul — Gratuito'), ('pro', 'Conexão Sul — R$ 197/ano'), ('producao', 'Destaque Sul — R$ 397/ano')], default='gratuito', max_length=20),
        ),
    ]
