# Generated by Django 5.2.2 on 2026-07-27 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='oferta',
            new_name='ofertas_ofe_status_efd35b_idx',
            old_name='ofertas_status_expira_idx',
        ),
        migrations.RenameIndex(
            model_name='oferta',
            new_name='ofertas_ofe_negocio_68e0aa_idx',
            old_name='ofertas_negocio_status_idx',
        ),
    ]
